### ISSUE TITLE
Usage of MN-COVID19

### ISSUE THREAD

**Issue by Vithar42** [coolbaby0208/MN-COVID19#2]
Not really an issue, but I had said I would share if I blended your work into mine...

My interactive Shiny Dashboard can be found here (Minnesota Tab):
https://commodorebacon.shinyapps.io/Shiny_Covid19/

git-repository here:
https://github.com/Vithar42/Shiny_Covid19

**Comment by coolbaby0208** [comment]
Cool! Was gonna try shiny some day. Thanks for sharing.
