### ISSUE TITLE
Moving average results

### ISSUE THREAD

**Issue by 2sls** [coolbaby0208/MN-COVID19#3]
Just a suggestion that the current moving average results look like they are equal weighting days - an alternative would be to weigh by the number of tests

This might make a difference because my calculations show an uptick in the positivity rate in the last week relative to the prior week which isn't visible in the current calculations.

**Comment by coolbaby0208** [comment]
![plot_zoom_png](https://user-images.githubusercontent.com/63076072/85335583-d8030680-b4a2-11ea-951a-75978fcb6588.png)

Is this what you are seeing?

**Comment by 2sls** [comment]
Ah yes there's the uptick :)
