### ISSUE TITLE
* breaks Currently.sick from websight

### ISSUE THREAD

**Issue by Vithar42** [coolbaby0208/MN-COVID19#4]
Yesterday the Currently.sick value was -952, until the website was updated.  Your code breaks because with the updated there is a * after the new value.   One way to remove the * and get the code working is if you change part of line 46 of mdhCovidWebScrape.R, the * and any other future punctuation that might screw things up...

Replace 
str_remove(",") 
with
str_replace_all("[[:punct:]]", "")

**Comment by coolbaby0208** [comment]
Thanks for catching the bug.
